### ISSUE TITLE
geary is not working

### ISSUE THREAD

**Issue by legacychimera247** [flathub/org.gnome.Geary#1]
geary ask me to input my mail then it tells me there are connection problems and can't configure my mail...this while the rpm version works well...any help?

**Comment by mjog** [comment]
Hi, please run Geary using this command from a terminal:

    flatpak run org.gnome.Geary -d

Then attach the output here to help debug the problem. Thank!

**Comment by legacychimera247** [comment]
thanks...that's the output
`Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
 [msg] 18:19:23 1,269807 geary-application.vala:243: Geary 0.12.0 prefix=/app exec_dir=/app/bin is_installed=true
 [deb] 18:19:24 1,493601 client-web-view.vala:138: Failed to load user CSS file: Apertura del file «/home/luca247/.var/app/org.gnome.Geary/config/geary/user-message.css» non riuscita: open() non riuscita: No such file or directory
 [deb] 18:19:25 0,775844 null-indicator.vala:13: No messaging menu support in this build
 [deb] 18:19:25 0,083849 geary-controller.vala:1614: No accounts found.
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
 [deb] 18:19:26 0,000118 web-process-extension.vala:19: Initialising...
 [deb] 18:19:42 17,479348 imap-client-session.vala:1469: [0000/imap-mail.outlook.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_CONNECTING] Connected to imap-mail.outlook.com/default:993
 [deb] 18:19:42 0,000008 imap-client-session.vala:624: [0000/imap-mail.outlook.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_CONNECTING] Connected
 [deb] 18:19:42 0,095893 imap-client-session.vala:1542: [0000/imap-mail.outlook.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_NOAUTH] capability #1: NAMESPACE IMAP4rev1 IMAP4 "AUTH=PLAIN" "AUTH=XOAUTH2" UNSELECT SASL-IR UIDPLUS CHILDREN ID LITERAL+ IDLE
 [deb] 18:19:42 0,000550 imap-client-session.vala:718: [0000/imap-mail.outlook.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_NOAUTH] use_starttls=false is_ssl=true starttls=false
 [deb] 18:19:42 0,000011 imap-client-session.vala:746: [0000/imap-mail.outlook.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_NOAUTH] No STARTTLS attempted
 [deb] 18:19:44 1,035806 imap-client-session.vala:1542: [0000/imap-mail.outlook.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_AUTHORIZED] capability #2: NAMESPACE IMAP4rev1 CLIENTNETWORKPRESENCELOCATION IMAP4 BACKENDAUTHENTICATE "AUTH=PLAIN" "AUTH=XOAUTH2" CLIENTACCESSRULES UNSELECT SASL-IR UIDPLUS MOVE CHILDREN ID LITERAL+ IDLE
 [deb] 18:19:44 0,000896 imap-client-session.vala:782: [0000/imap-mail.outlook.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_AUTHORIZED] No compression available
 [deb] 18:19:44 0,000094 imap-deserializer.vala:250: [des:0000/GEARY_IMAP_DESERIALIZER_STATE_TAG] Waiting for deserializer to close...
 [deb] 18:19:44 0,000157 imap-deserializer.vala:809: [des:0000/GEARY_IMAP_DESERIALIZER_STATE_TAG] input error: L'operazione è stata annullata
 [deb] 18:19:44 0,000161 imap-deserializer.vala:252: [des:0000/GEARY_IMAP_DESERIALIZER_STATE_CLOSED] Deserializer closed
 [deb] 18:19:44 0,000067 imap-client-connection.vala:422: [0000/imap-mail.outlook.com/default:993/GEARY_IMAP_CLIENT_CONNECTION_STATE_CONNECTED] Disconnecting...
 [deb] 18:19:44 0,000591 imap-client-connection.vala:425: [0000/imap-mail.outlook.com/default:993/GEARY_IMAP_CLIENT_CONNECTION_STATE_CONNECTED] Disconnected
 [deb] 18:19:44 0,000021 imap-client-session.vala:1475: [0000/imap-mail.outlook.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_BROKEN] Disconnected from imap-mail.outlook.com/default:993
 [deb] 18:19:44 0,000529 imap-client-session.vala:406: DTOR: ClientSession imap-mail.outlook.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_BROKEN
 [deb] 18:19:54 10,392965 geary-engine.vala:370: Error validating SMTP account info: Errore nel risolvere «smtp-mail.outlook.com»: Temporary failure in name resolution
 [deb] 18:19:54 0,101427 geary-controller.vala:889: Validation failed. Prompting user for revised account information
`
by the way...seems that the flatpak file is not working and the app only install via terminal...i need to open a new issue for that?

**Comment by mjog** [comment]
Thanks for that. Looking at the logs, it's connecting to IMAP fine, but it's failing to look up the SMTP server host name. Can you try the following in a terminal and see if it works?

> host smtp-mail.outlook.com

Also, when you're creating the account are you selecting Outlook.com as the service, or are you manually entering the connection details?

About the flatpak file - we're just using Flatpak and Flathub as-is, so if there's an issue installing it it would be worth reporting against Flatpak itself.

**Comment by legacychimera247** [comment]
tried with outlook and manual entering...i will try your command but consider evolution has the same account (and another outlook) running just fine, and that the rpm version of geary has always worked...

**Comment by legacychimera247** [comment]
anyway that's the output for your command

`smtp-mail.outlook.com is an alias for smtp.live.com.
smtp.live.com is an alias for smtp.glbdns2.microsoft.com.
smtp.glbdns2.microsoft.com is an alias for smtp.office365.com.
smtp.office365.com is an alias for smtp.outlook.office365.com.
smtp.outlook.office365.com is an alias for outlook.office365.com.
outlook.office365.com is an alias for outlook.ha.office365.com.
outlook.ha.office365.com is an alias for outlook.office365.com.g.office365.com.
outlook.office365.com.g.office365.com is an alias for outlook-emeasouth3.office365.com.
outlook-emeasouth3.office365.com has address 40.101.55.98
outlook-emeasouth3.office365.com has address 40.101.61.114
outlook-emeasouth3.office365.com has address 40.101.76.162
outlook-emeasouth3.office365.com has address 40.101.72.114
outlook-emeasouth3.office365.com has address 40.101.45.82
outlook-emeasouth3.office365.com has address 40.101.49.82
outlook-emeasouth3.office365.com has address 40.101.12.66
outlook-emeasouth3.office365.com has address 40.101.48.66
outlook-emeasouth3.office365.com has IPv6 address 2603:1026:6:28::2
outlook-emeasouth3.office365.com has IPv6 address 2603:1026:3:a3::2
outlook-emeasouth3.office365.com has IPv6 address 2603:1026:203:8c::2
outlook-emeasouth3.office365.com has IPv6 address 2603:1026:301:2b::2
outlook-emeasouth3.office365.com has IPv6 address 2603:1026:3:78::2
outlook-emeasouth3.office365.com has IPv6 address 2603:1026:206:4::2
outlook-emeasouth3.office365.com has IPv6 address 2603:1026:300:c8::2
outlook-emeasouth3.office365.com has IPv6 address 2603:1026:4:8d::2
`

**Comment by mjog** [comment]
Hey, apologies for the delay. This seems to be a systemd-resolved bug, not a Geary bug. Not that you will be unable to connect using telnet, either: `telnet smtp-mail.outlook.com imap` will return the same error.

If you are using Ubuntu 17.10, I have filed a LP bug about it: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1728560

As a workaround, you can add `smtp-mail.outlook.com` to your `/etc/hosts` file, [per this message](https://mail.gnome.org/archives/geary-list/2017-October/msg00032.html) on the mailing list.

**Comment by legacychimera247** [comment]
i am on fedora 26...anyway i've tried fedora 27 beta and geary was working fine so i assume i just need to wait till fedora 27 is officially released... :)

**Comment by jurf** [comment]
Hm, I’m using Geary and Outlook on F26 just fine…

**Comment by aviwad** [comment]
For anyone reading here, confused. The solution was to change the SSL type to "STARTSSL" instead of "TLS"
