### ISSUE TITLE
Opening Geary from desktop file does not always work

### ISSUE THREAD

**Issue by bastianilso** [flathub/org.gnome.Geary#20]
I am occassionally experiencing issues opening Geary from the *.desktop file provided by the flatpak. The Geary application window never appears, but GNOME Shell indicates that Geary is open. Closing it is not possible so I have to go to System Monitor to kill the process. I cannot reproduce it consistently. I don't know if opening from commandline with `flatpak run org.gnome.Geary` is affected as well, but so far I haven't problems when doing this.

**Comment by mjog** [comment]
Hey, thanks for the bug report. Does this ever happen when starting Geary for the first time after login? Or put another way, does it only happen after Geary was previously running? I'm wondering if it's not getting shut down properly when quit.

**Comment by mjog** [comment]
Closing due to lack of response. Please reopen if you can provide the information. Thanks!
