### ISSUE TITLE
Autostart doesn’t work

### ISSUE THREAD

**Issue by jurf** [flathub/org.gnome.Geary#3]
This is per flatpak/flatpak#118, just wanted to document it here for when it gets fixed.

**Comment by mjog** [comment]
Thanks for the bug report. Upstream bug reported at b.g.o: https://bugzilla.gnome.org/show_bug.cgi?id=789679

A fix using `--filesystem=xdg-config/autostart:create ` shouldn't be too far off.

**Comment by TingPing** [comment]
That also bypasses any chance of calling this sandboxed since you directly grant the ability to run arbitrary commands on the host.

**Comment by mjog** [comment]
@TingPing Yeah, I suspect you'd say that. :) So would you say it is an inappropriate workaround for an app on FlatHub?

**Comment by TingPing** [comment]
I guess we can live with it in the short-term but it is not a great solution.

**Comment by bellegarde-c** [comment]
This is fixed by 43.0 release (using xdg background portal)
