### ISSUE TITLE
No icon in notifications

### ISSUE THREAD

**Issue by jurf** [flathub/org.gnome.Geary#4]
I remember it being there in the native installation, but correct me if I’m wrong.

(F27)

**Comment by TingPing** [comment]
This uses `rename-icon` so probably needs a patch in code to refer to the new icon name.

**Comment by mjog** [comment]
This is probably because of [Bug 790103](https://bugzilla.gnome.org/show_bug.cgi?id=790103)

**Comment by jurf** [comment]
Thanks!

**Comment by mjog** [comment]
This was fixed in 0.12.2.
