### ISSUE TITLE
Fails to add Gmail account

### ISSUE THREAD

**Issue by luksireiku** [flathub/org.gnome.Geary#6]
Shows message about username or password incorrect, but I tried them at gmail and works.

**Comment by mjog** [comment]
You probably need to update some Google Account settings to make this work, per the FAQ entry: https://wiki.gnome.org/Apps/Geary/FAQ#Connecting_to_GMail

Support for Google's proprietary extension is happening over in [Bug 746705](https://bugzilla.gnome.org/show_bug.cgi?id=746705).

**Comment by luksireiku** [comment]
Thanks, that made it work
