### ISSUE TITLE
No email providers

### ISSUE THREAD

**Issue by faveoled** [flathub/org.gnome.Geary#66]
Ubuntu 22.04. Non-flatpak version does have providers
![Screenshot from 2024-02-16 19-05-58](https://github.com/flathub/org.gnome.Geary/assets/85760289/cfe1b83b-dafa-498a-883e-ef3261df2b4d)

**Comment by fedelibre** [comment]
I can confirm the same problem on Fedora Silverblue. When I try to add another account I'm not offered the choice of a provider, but I can only enter the information manually. I'll check  Geary RPM on Fedora workstation tomorrow.

These are the current default permissions of Geary flatpak from Flathub:

```
$ flatpak info --show-permissions org.gnome.Geary
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;fallback-x11;
devices=dri;
filesystems=xdg-download;/tmp;~/.cache/evolution/addressbook:ro;~/.config/geary:ro;

[Session Bus Policy]
org.gnome.ControlCenter=talk
org.gnome.Contacts=talk
org.freedesktop.secrets=talk
org.gnome.OnlineAccounts=talk
org.gnome.evolution.dataserver.*=talk
```

@bellegarde-c Do you see any permission missing?

**Comment by bellegarde-c** [comment]
Just an issue in Geary. Click add button...

**Comment by bellegarde-c** [comment]
> I can confirm the same problem on Fedora Silverblue. When I try to add another account I'm not offered the choice of a provider, but I can only enter the information manually. I'll check Geary RPM on Fedora workstation tomorrow.

Geary does auto detect provider based on email.

**Comment by faveoled** [comment]
> Click add button...

It proceeds to manual configuration. I expect it to have preconfigured defaults for GMail and other services just as the non-flatpaked app

**Comment by fedelibre** [comment]
> > I can confirm the same problem on Fedora Silverblue. When I try to add another account I'm not offered the choice of a provider, but I can only enter the information manually. I'll check Geary RPM on Fedora workstation tomorrow.
> 
> Geary does auto detect provider based on email.

Ok, but it seems that Geary flatpak is not able to talk to GNOME control center.
I'm now testing Geary RPM (Fedora workstation) and if I add a new @gmail.com account I'm redirected to the Online accounts of the control center. This does not happen with Geary flatpak.
