### ISSUE TITLE
Geary 46

### ISSUE THREAD

**Issue by eisenspiel** [flathub/org.gnome.Geary#67]
Hi. Please update the package. There's 46 already.

**Comment by davidlamkin** [comment]
Looks like the build was [successful](https://buildbot.flathub.org/#/builders/6/builds/126488) last week. Do we know the timeline as to when [Geary 46 ](https://github.com/GNOME/geary/tree/46.0)will be published to Flathub?

**Comment by davidlamkin** [comment]
Nobody?

**Comment by mcatanzaro** [comment]
I guess there is some sort of infrastructure problem. The changes are landed and master branch CI is green.

**Comment by bbhtt** [comment]
Triggered a build at https://buildbot.flathub.org/#/builders/6/builds/130949

**Comment by bbhtt** [comment]
Should be published now.
