### ISSUE TITLE
Network unreachable connecting to mail servers

### ISSUE THREAD

**Issue by vibolvireak** [flathub/org.gnome.Geary#9]
Operation System | Flatpak Version | Desktop Environment
--- | --- |  ---
Fedora 27 | 0.99.3 | Gnome 3.26.2

After successful login with gmail account. Geary only show outbox nothing else display.

![screenshot from 2018-08-10 16-30-46](https://user-images.githubusercontent.com/6574345/43950586-e0d44028-9cba-11e8-952d-cc13585bfc6f.png)

**Below is a log when run** `flatpak run org.gnome.Geary -d`

`[msg] 16:13:59 0.135218 geary-application.vala:253: Geary 0.12.3 prefix=/app exec_dir=/app/bin is_installed=true`
`[deb] 16:13:59 0.163945 client-web-view.vala:140: Failed to load user CSS file: Failed to open file “/home/fedora/.var/app/org.gnome.Geary/config/geary/user-message.css”: open() failed: No such file or directory`
`[deb] 16:13:59 0.081446 null-indicator.vala:13: No messaging menu support in this build`
`[deb] 16:13:59 0.011945 util-connectivity-manager.vala:68: Checking if imap.gmail.com/default:993 reachable...`
`[deb] 16:13:59 0.101017 util-connectivity-manager.vala:85: Error checking imap.gmail.com/default:993 reachable, treating as unreachable: Network unreachable`
`[deb] 16:14:00 0.535786 db-versioned-database.vala:77: VersionedDatabase.upgrade: current database schema for /home/fedora/.var/app/org.gnome.Geary/data/geary/account_02/geary.db: 25`
`[deb] 16:14:00 0.001574 imap-db-gc.vala:105: [GC:/home/fedora/.var/app/org.gnome.Geary/data/geary/account_02/geary.db] GC state: last_reap_time=never last_vacuum_time=never reaped_messages_since=0 free_page_bytes=4096`
`[deb] 16:14:00 0.000052 imap-db-gc.vala:119: [GC:/home/fedora/.var/app/org.gnome.Geary/data/geary/account_02/geary.db] Recommending reaping: never completed`
`[deb] 16:14:00 0.000006 imap-db-gc.vala:138: [GC:/home/fedora/.var/app/org.gnome.Geary/data/geary/account_02/geary.db] Database never vacuumed (0 messages reaped)`
`[deb] 16:14:00 0.000018 imap-db-gc.vala:254: [GC:/home/fedora/.var/app/org.gnome.Geary/data/geary/account_02/geary.db] Starting garbage collection of IMAP database`
`[deb] 16:14:00 0.000068 imap-db-gc.vala:283: [GC:/home/fedora/.var/app/org.gnome.Geary/data/geary/account_02/geary.db] Garbage collector reaping date: 2018-07-11T16:14:00+0700 (1531300440)`
`[deb] 16:14:00 0.003969 smtp-outbox-folder.vala:178: Starting outbox postman`
`[msg] 16:14:00 0.001156 imap-db-gc.vala:312: [GC:/home/fedora/.var/app/org.gnome.Geary/data/geary/account_02/geary.db] Found 0 email messages ready for reaping`
`[msg] 16:14:00 0.000125 imap-db-gc.vala:343: [GC:/home/fedora/.var/app/org.gnome.Geary/data/geary/account_02/geary.db] Reaped completed: 0 messages`
`[msg] 16:14:00 0.001288 imap-db-gc.vala:366: [GC:/home/fedora/.var/app/org.gnome.Geary/data/geary/account_02/geary.db] Completed: Reaped 0 attachment files`
`[msg] 16:14:00 0.000189 imap-db-database.vala:88: Garbage collection of IMAP database /home/fedora/.var/app/org.gnome.Geary/data/geary/account_02/geary.db failed: Error opening directory '/home/fedora/.var/app/org.gnome.Geary/data/geary/account_02/attachments': No such file or directory`
`[deb] 16:14:00 0.029428 smtp-outbox-folder.vala:141: Filling outbox queue`
`[deb] 16:14:00 0.108641 imap-client-session-manager.vala:305: Error creating session: Host at imap.gmail.com/default:993 is unreachable`
`[deb] 16:14:00 0.000026 imap-engine-generic-account.vala:410: Refresh of account Gmail:account_02 folders did not complete: Host at imap.gmail.com/default:993 is unreachable`
`[deb] 16:14:05 5.519518 imap-db-account.vala:1585: account_02: Populating search table`
`[deb] 16:14:05 0.000011 imap-db-account.vala:1620: account_02: Searching for up to 50 missing indexed messages...`
`[deb] 16:14:05 0.001515 imap-db-account.vala:1602: account_02: Done populating search table`

**Comment by mjog** [comment]
Hi, thanks for the bug report. It seems like certain people are finding Geary no longer connects to outside networks. I cannot reproduce it locally, so can you provide the following information:

 * Your desktop (GNOME? KDE? Something else?)
 * Your operating system and version (Ubuntu 16.04? Fedora 28? Rolled your own?)

Also, can you say if your computer is using Network Manager for connecting to the Internet? Thanks!

**Comment by vibolvireak** [comment]
@mjog 

I have updated information on my environment.

**Comment by vibolvireak** [comment]
I have updated information for my environment.

Operation System | Flatpak Version | Desktop Environment
--- | --- |  ---
Fedora 27 | 0.99.3 | Gnome 3.26.2

**Remark!**

Testing Geary on ElementaryOS live iso and connect to my gmail account is working really fine so i'm completely sure that my internet can reach google server fine.

**Comment by Exalm** [comment]
Same on Fedora Silverblue 28, Flatpak 0.99.3.
```
 ~/Projects/gnome-games  flatpak info org.gnome.Geary   
Ref: app/org.gnome.Geary/x86_64/stable
ID: org.gnome.Geary
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-07-14 03:17:19 +0000
Subject: Update for 0.12.3. (f28280d6)
Commit: d3e99d2c6323d742a45ada4fff8c8f35e2dbd1483a1763df4c71f66ce2c50fab
Parent: 1e534785825be1fa7144a5a9c0ea6c656bf41fd3a5371938e1adc646b67033f8
Location: /var/lib/flatpak/app/org.gnome.Geary/x86_64/stable/d3e99d2c6323d742a45ada4fff8c8f35e2dbd1483a1763df4c71f66ce2c50fab
Installed size: 6.9 MB
Runtime: org.gnome.Platform/x86_64/3.28
Sdk: org.gnome.Sdk/x86_64/3.28
 ~/Projects/gnome-games  flatpak info org.gnome.Platform//3.28
Ref: runtime/org.gnome.Platform/x86_64/3.28
ID: org.gnome.Platform
Arch: x86_64
Branch: 3.28
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-08-06 22:24:22 +0000
Subject: build of org.gnome.Sdk, Mon Aug  6 13:44:56 UTC 2018
Commit: cd176f8f59d2bf3177d7b1cecceb9af1059196e3183eea915b1898a47decb179
Parent: cc7c2dd516160674998803e6ed6838091d628a3d25ff7465485ddecfb9f4363f
Location: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.28/cd176f8f59d2bf3177d7b1cecceb9af1059196e3183eea915b1898a47decb179
Installed size: 1.3 GB
```

**Comment by jurf** [comment]
@Exalm that’s weird, same setup here, no problem. Though maybe just two things to note: my Geary setup is migrated from the classic F28 I had (just moved .var) and I override the DNS servers locally, otherwise nothing interesting.

**Comment by jurf** [comment]
Well, maybe, mine was just Flatpak → Flatpak, not native → Flatpak, maybe there’s some version or dependency version inconsistency causing this.

**Comment by mjog** [comment]
This is looking like a GLib/GIO/Flatpak/portal issue, to confirm, can I get you all to try the following please: Open a terminal and run the command `flatpak run --devel --command=bash org.gnome.Geary` (you may need to install the org.gnome.Sdk//3.28 flatpak runtime first to make this work). That will give you a flatpak shell, then run `python3`, and paste the following script into the python shell:

```
from gi.repository import Gio
monitor = Gio.NetworkMonitor.get_default()
monitor.get_connectivity()
monitor.can_reach(Gio.NetworkAddress.new('imap.gmail.com', 993), None)
```

And paste result of the last two lines here? Thanks.

For those of you on Fedora, did you notice a flatpak/xdg-desktop-portal/xdg-desktop-portal-gtk package update recently?

**Comment by mjog** [comment]
Quick update, this seems to be caused by [xdg-desktop-portal issue #208](https://github.com/flatpak/xdg-desktop-portal/issues/208).

Until that gets fixed, a workaround would be revert to the last version, or as suggested in the upstream issue killing xdg-desktop-portal might help.

**Comment by mjog** [comment]
A workaround for the portal bug is currently building and will be pushed to Flathub soon.

Can you try updating and let me know if it works for you? Thanks!

**Comment by vibolvireak** [comment]
@mjog It's now finally work so feel free to close this issue

**Comment by mjog** [comment]
Great, thanks for confirming.

Apologies for taking so long, I assumed the runtimes would have been fixed petty quickly since it's a major regression, but in retrospect I should have looked into a workaround sooner.
